apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80 # Porta do serviço
    targetPort: 80 # Porta do container
    nodePort: 30080  
  selector:
    app: nginx