apiVersion: apps/v1
kind: Deployment
metadata:    
    name: nginx
spec:    
    replicas: 1
    selector:    
        matchLabels:    
            app: nginx
    template:    
        metadata:    
            labels:    
                app: nginx
        spec:    
            containers:    
            - name: nginx
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              ports:    
              - containerPort: 80
              volumeMounts:
              - name: nginx-config
                mountPath: /etc/nginx/conf.d
            volumes:
            - name: nginx-config
              configMap:
                name: nginx-config
---
apiVersion: v1
kind: Service
metadata:    
    name: prometheus-service
spec:    
    type: NodePort
    ports:    
    - port: 9090
      targetPort: 9090
      nodePort: 30002
    selector:    
        app: prometheus